// Code generated by json2struct DO NOT EDIT

package config

// Config1 autogenerated
type Config1 struct {
	MysqlParameters          map[string]interface{} `json:"mysqlParameters"`
	MysqlAggregateHost       string                 `json:"mysqlAggregateHost"`
	DynamoDBS3BucketName     string                 `json:"dynamoDBS3BucketName"`
	PasswordPepper           string                 `json:"passwordPepper"`
	AwsAndroidPushARN        string                 `json:"awsAndroidPushARN"`
	MysqlUser                string                 `json:"mysqlUser"`
	MysqlHost                string                 `json:"mysqlHost"`
	JwtSigningSecret         string                 `json:"jwtSigningSecret"`
	AwsAccessKey             string                 `json:"awsAccessKey"`
	AwsAccessSecret          string                 `json:"awsAccessSecret"`
	MysqlAggregateProtocol   string                 `json:"mysqlAggregateProtocol"`
	MysqlAggregateParameters map[string]interface{} `json:"mysqlAggregateParameters"`
	MysqlAggregateDatabase   string                 `json:"mysqlAggregateDatabase"`
	MysqlAggregatePort       float64                `json:"mysqlAggregatePort"`
	DynamoDBTable            string                 `json:"dynamoDBTable"`
	MetadataVersion          string                 `json:"metadataVersion"`
	AwsRegion                string                 `json:"awsRegion"`
	MysqlProtocol            string                 `json:"mysqlProtocol"`
	MysqlAggregatePassword   string                 `json:"mysqlAggregatePassword"`
	MysqlDatabase            string                 `json:"mysqlDatabase"`
	MysqlPort                float64                `json:"mysqlPort"`
	MysqlAggregateUser       string                 `json:"mysqlAggregateUser"`
	Version                  string                 `json:"version"`
	AwsiOSPushARN            string                 `json:"awsiOSPushARN"`
	PreferredLanguage        string                 `json:"preferredLanguage"`
	MysqlPassword            string                 `json:"mysqlPassword"`
}

// Config2 autogenerated
type Config2 struct {
	AwsAccessKey             string                 `json:"awsAccessKey"`
	AwsAccessSecret          string                 `json:"awsAccessSecret"`
	MysqlPassword            string                 `json:"mysqlPassword"`
	MysqlPort                float64                `json:"mysqlPort"`
	DynamoDBTable            string                 `json:"dynamoDBTable"`
	JwtSigningSecret         string                 `json:"jwtSigningSecret"`
	Version                  string                 `json:"version"`
	PreferredLanguage        string                 `json:"preferredLanguage"`
	MysqlAggregateProtocol   string                 `json:"mysqlAggregateProtocol"`
	MetadataVersion          string                 `json:"metadataVersion"`
	AwsiOSPushARN            string                 `json:"awsiOSPushARN"`
	MysqlAggregateUser       string                 `json:"mysqlAggregateUser"`
	MysqlAggregateHost       string                 `json:"mysqlAggregateHost"`
	MysqlAggregatePort       float64                `json:"mysqlAggregatePort"`
	MysqlUser                string                 `json:"mysqlUser"`
	MysqlProtocol            string                 `json:"mysqlProtocol"`
	MysqlHost                string                 `json:"mysqlHost"`
	MysqlParameters          map[string]interface{} `json:"mysqlParameters"`
	MysqlAggregatePassword   string                 `json:"mysqlAggregatePassword"`
	MysqlAggregateParameters map[string]interface{} `json:"mysqlAggregateParameters"`
	DynamoDBS3BucketName     string                 `json:"dynamoDBS3BucketName"`
	AwsRegion                string                 `json:"awsRegion"`
	MysqlDatabase            string                 `json:"mysqlDatabase"`
	MysqlAggregateDatabase   string                 `json:"mysqlAggregateDatabase"`
	PasswordPepper           string                 `json:"passwordPepper"`
	AwsAndroidPushARN        string                 `json:"awsAndroidPushARN"`
}
